# Sanity Automation Framework Configuration

modules:
  reboot: false
  audio: false
  camera: true
  connectivity: true
  sensors_power: false
  sensors_advanced: true
  nfc: true
  gps: true
  
network:
  wifi_ssid: "Xiaomi_test"
  wifi_pass: "0987654321"
